Array Numpy

In [5]:
import numpy as np
x = np.array([[4, 4, 6], [5, 7,3]])
print(x)

[[4 4 6]
 [5 7 3]]


In [7]:
#Создаем 2D массив NumPy с единицами по главной диагонали и нулями в остальных ячейках
from scipy import sparse
eye = np.eye(4)
print(eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
# Преобразовываем массив NumPy в разреженную матрицу SciPy в формате CSR
# Сохраняем лишь ненулевые элементы
sparse_matrix = sparse.coo_matrix(eye)
print("формат C00:\n{}".format(sparse_matrix))

формат C00:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
